- README.md
- connect.sh
- files/docker/bin/dockerd-wrapper
- files/edge-core/patches/0003-Broadcast-gateway-stats-to-LWM2M-resources.patch
- files/kubelet/scripts/launch-kubelet.sh
- snap/snapcraft.yaml
Clean up error messages from snappy-debug
> Strict mode cleanup

- snap/snapcraft.yaml
Pull in intitial LTE configuration support
> Upgrade maestro version

- snap/snapcraft.yaml
Include changes for configuring an LTE interface.
> Bump Maestro-shell version

- snap/snapcraft.yaml
Update maestro to include modem management functionality and add plugs
to permit this functionality.
> Upgrade maestro

- files/edge-core/scripts/edge-core-factory-reset
When a factory reset is sent we will now clear the userdata and
the maestroconfig.db
> clearing MaestroDB

- files/kubelet/scripts/launch-kubelet.sh
The kubelet launch script now exits if it can't get a valid IP
causing the service to attempt an auto restart.
> Fix Bogus DNS Queries

- files/platform-version/platform-version.sh
- snap/snapcraft.yaml
> Add platform-version script

- snap/snapcraft.yaml
Fixes bug regarding existing flag for nameserver settings
> Update maestro hash

- snap/snapcraft.yaml
Update maestro-shell to include wifi support
> update maestro-shell 

- files/edge-core/scripts/edge-core-bootloader.sh
Signed-off-by: Cristian Prundeanu <cristian.prundeanu@arm.com>
> Add watch mechanism for snap refresh

- files/edge-core/scripts/edge-core-bootloader.sh
firmware upgrades will be handled by snap-refresh rather than
side-loading snaps through Pelion.
> rework firmware upgrade process

- files/edge-core/scripts/edge-core-bootloader.sh
- files/edge-core/scripts/launch-edge-core.sh
> Map version hash to human readable string

- files/identity/launch-pelion-identity.sh
the linux build checks for the existence of identity.json in a
nicer way.
> identity: make launch script consistent with the linux build

- files/kubelet/scripts/launch-kubelet.sh
- snap/snapcraft.yaml
Do not merge until after:
https://github.com/PelionIoT/snap-pelion-edge/pull/333
> v1.20.2 (master)

- entrypoint.sh
- snap/snapcraft.yaml
this should alleviate ssh key issues when using the docker
container for builds.
> switch all repo URIs to https

- snap/snapcraft.yaml
Update to the latest master branch of edge-proxy.
> Update edge-proxy SHA

- Dockerfile
Signed-off-by: Cristian Prundeanu <cristian.prundeanu@arm.com>
> Remove active empty ENV parameters and add details to comment

- snap/snapcraft.yaml
Trying to help out with https://go.arm.com/xjpLL53
> trying this little fix for Sajith

- snap/hooks/configure
Signed-off-by: Cristian Prundeanu <cristian.prundeanu@pelion.com>
> Add default value for kubelet.container-signing

- files/kubelet/scripts/launch-kubelet.sh
Signed-off-by: Cristian Prundeanu <cristian.prundeanu@pelion.com>
> Fix logic for signing-mode socket selection

- snap/snapcraft.yaml
Add multiple connections support.
> Update bouncer to v1.1.0

- .github/workflows/align-pe-utils.yml
- .github/workflows/build.yml
Enable manual builds with given branch.
Update checkout to latest version.
> PR - build also with manual trigger, use checkout v4
